# Use root/example as user/password credentials
version: '3.1'

services:

  db_payments:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
    - 3306:3306
    networks:
        mynetwork4:
          ipv4_address: 10.9.0.4

  api_payments:
      container_name: payments_api      
      build:
        context: .
        dockerfile: dockerfile
      volumes:
      - '.:/usr/src/app'  
      ports:
        - 7002:5000
      networks:
        mynetwork4:
          ipv4_address: 10.9.0.2


networks:
  mynetwork4:
    driver: bridge
    ipam:
     config:
       - subnet: 10.9.0.0/16
