---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: gasalho
  labels:
    app:  payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: payment-db
        image: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secrets
              key: db_root_password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: gasalho
  labels:
    app: payment-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: payment-db