---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: lucia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: registry.deti:5000/lucia/api-payment:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: fileManager
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: lucia
spec:
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer