version: "3.9"
   
services:
  db_video_sharing:
    image: postgres
    volumes:
      - db_video_sharing_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_video_sharing
      - POSTGRES_USER=videoadmin
      - POSTGRES_PASSWORD=videoadmin
    networks:
        - internal
  web:
    build:
        context: .
        dockerfile: ./video_sharing/Dockerfile

    command: bash -c "sleep 5 && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=db_video_sharing
      - POSTGRES_USER=videoadmin
      - POSTGRES_PASSWORD=videoadmin
    depends_on:
      - db_video_sharing
    networks:
        - internal
volumes:
  db_video_sharing_data:

networks:
  internal:
    external:
      name: "internal"