---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filemanager-db
  namespace: egs10
  labels:
    app: testdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdb
  template:
    metadata:
      labels:
        app: testdb
    spec:
      containers:
      - name: filemanager-db
        image: mysql
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filemanagerapi-secrets
              key: DB_PASSWORD
        ports:
        - containerPort: 3306
          name: testdb-contain
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv3-claim
---
apiVersion: v1
kind: Service
metadata:
  name: filemanager-db-service
  namespace: egs10
  labels:
    app: testdb
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: filemanager-db-service
  selector:
    app: testdb