# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict

from base_model_ import Model
import util
class Confirm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, client: object=None):  # noqa: E501
        """Confirm - a model defined in Swagger

        :param client: The client of this Confirm.  # noqa: E501
        :type client: object
        """
        self.swagger_types = {
            'client': object
        }

        self.attribute_map = {
            'client': 'client'
        }
        self._client = client

    @classmethod
    def from_dict(cls, dikt) -> 'Confirm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Confirm of this Confirm.  # noqa: E501
        :rtype: Confirm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client(self) -> object:
        """Gets the client of this Confirm.


        :return: The client of this Confirm.
        :rtype: object
        """
        return self._client

    @client.setter
    def client(self, client: object):
        """Sets the client of this Confirm.


        :param client: The client of this Confirm.
        :type client: object
        """
        if client is None:
            raise ValueError("Invalid value for `client`, must not be `None`")  # noqa: E501

        self._client = client
