# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime
import imp  # noqa: F401

from typing import List, Dict
from base_model_ import Model
class Transaction(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, wallet: object=None):  # noqa: E501
        """Transaction - a model defined in Swagger

        :param wallet: The wallet of this Transaction.  # noqa: E501
        :type wallet: object
        """
        self.swagger_types = {
            'wallet': object
        }

        self.attribute_map = {
            'wallet': 'wallet'
        }
        self._wallet = wallet

    @classmethod
    def from_dict(cls, dikt) -> 'Transaction':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Transaction of this Transaction.  # noqa: E501
        :rtype: Transaction
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wallet(self) -> object:
        """Gets the wallet of this Transaction.


        :return: The wallet of this Transaction.
        :rtype: object
        """
        return self._wallet

    @wallet.setter
    def wallet(self, wallet: object):
        """Sets the wallet of this Transaction.


        :param wallet: The wallet of this Transaction.
        :type wallet: object
        """
        if wallet is None:
            raise ValueError("Invalid value for `wallet`, must not be `None`")  # noqa: E501

        self._wallet = wallet
