# Use root/example as user/password credentials
version: '3.1'

services:

  db_auth:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
    - 3306:3306
    networks:
        mynetwork3:
          ipv4_address: 10.8.0.4
  
  adminer_auth:
    image: adminer
    restart: always
    ports:
      - 4321:8080
    networks:
        mynetwork3:
          ipv4_address: 10.8.0.3 

  api_auth:
      container_name: auth_api      
      build:
        context: .
        dockerfile: dockerfile
      volumes:
      - '.:/usr/src/app'  
      ports:
        - 7001:5000
      networks:
        mynetwork3:
          ipv4_address: 10.8.0.2


networks:
  mynetwork3:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.0.0/16
